- id: append-jira-issue
  name: Append Jira Issue
  entry: append_jira_issue
  language: python
  description: This hook appends a Jira issue to a commit message
  always_run: true
  stages: [commit-msg]
